import { Chord } from 'tonal';
import type { Song, Measure, ChordInfo } from '../types/music';
import { Gjazz } from './gjazzData';
import { Ol55 } from './ol55Data';

function ch(symbol: string): ChordInfo {
  const c = Chord.get(symbol);
  return {
    symbol,
    root: c.tonic || symbol.match(/^[A-G][b#]?/)?.[0] || '',
    quality: c.type || '',
    notes: c.notes.length ? c.notes : [],
  };
}

function m(chords: string[], section?: string): Measure {
  return {
    chords: chords.filter(Boolean).map(ch),
    section,
  };
}

export const DEMO_SONGS: Song[] = [
  {
    title: 'Blue Bossa',
    composer: 'Kenny Dorham',
    style: 'Bossa Nova',
    key: 'Cm',
    bpm: 160,
    timeSignature: '4/4',
    measures: [
      m(['Cm7'], 'A'),
      m(['Cm7']),
      m(['Fm7']),
      m(['Fm7']),
      m(['Dm7b5']),
      m(['G7']),
      m(['Cm7']),
      m(['Cm7']),
      m(['Ebm7'], 'B'),
      m(['Ab7']),
      m(['Dbmaj7']),
      m(['Dbmaj7']),
      m(['Dm7b5']),
      m(['G7']),
      m(['Cm7']),
      m(['Cm7']),
    ],
  },
  {
    title: 'Autumn Leaves',
    composer: 'Joseph Kosma',
    style: 'Medium Swing',
    key: 'Gm',
    bpm: 140,
    timeSignature: '4/4',
    measures: [
      m(['Cm7'], 'A'),
      m(['F7']),
      m(['Bbmaj7']),
      m(['Ebmaj7']),
      m(['Am7b5']),
      m(['D7']),
      m(['Gm']),
      m(['Gm']),
      m(['Cm7'], 'A'),
      m(['F7']),
      m(['Bbmaj7']),
      m(['Ebmaj7']),
      m(['Am7b5']),
      m(['D7']),
      m(['Gm']),
      m(['Gm']),
      m(['Am7b5'], 'B'),
      m(['D7']),
      m(['Gm']),
      m(['Gm']),
      m(['Cm7']),
      m(['F7']),
      m(['Bbmaj7']),
      m(['Ebmaj7']),
      m(['Am7b5'], 'C'),
      m(['D7']),
      m(['Gm']),
      m(['Gm']),
    ],
  },
  {
    title: 'All The Things You Are',
    composer: 'Jerome Kern',
    style: 'Medium Swing',
    key: 'Ab',
    bpm: 132,
    timeSignature: '4/4',
    measures: [
      m(['Fm7'], 'A'),
      m(['Bbm7']),
      m(['Eb7']),
      m(['Abmaj7']),
      m(['Dbmaj7']),
      m(['G7']),
      m(['Cmaj7']),
      m(['Cmaj7']),
      m(['Cm7'], 'B'),
      m(['Fm7']),
      m(['Bb7']),
      m(['Ebmaj7']),
      m(['Abmaj7']),
      m(['D7']),
      m(['Gmaj7']),
      m(['Gmaj7']),
      m(['Am7'], 'C'),
      m(['D7']),
      m(['Gmaj7']),
      m(['Gmaj7']),
      m(['F#m7']),
      m(['B7']),
      m(['Emaj7']),
      m(['C7']),
      m(['Fm7'], 'A'),
      m(['Bbm7']),
      m(['Eb7']),
      m(['Abmaj7']),
      m(['Dbmaj7']),
      m(['Dbm7']),
      m(['Cm7']),
      m(['Bdim7']),
      m(['Bbm7']),
      m(['Eb7']),
      m(['Abmaj7']),
      m(['Abmaj7']),
    ],
  },
  ...Gjazz,
  ...Ol55,
];
